# This rule is not used by the project kaddy-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gateway.kaddy.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kaddy-operator
    app.kubernetes.io/managed-by: kustomize
  name: caddy-viewer-role
rules:
- apiGroups:
  - gateway.kaddy.io
  resources:
  - caddies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.kaddy.io
  resources:
  - caddies/status
  verbs:
  - get
