---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gateway.kaddy.io
  resources:
  - caddies
  - caddysites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.kaddy.io
  resources:
  - caddies/finalizers
  - caddysites/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.kaddy.io
  resources:
  - caddies/status
  - caddysites/status
  verbs:
  - get
  - patch
  - update
