apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc-client
    namespace: argocd
    labels:
        app.kubernetes.io/name: argocd-oidc-client
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:0EZ28ijn3/ScDcKV5oy2h8Lh4jbHw5Qy3g/WFKFJOE4raC44WuaKGPHqmZR0OZYpwwUmfk/VooyVy5yu6fbhUg==,iv:CH8d/W6koKukS3025Af0v+yJYvMALpoluOB5JDGoy4c=,tag:aXLAGhKVVCVYCWi75O1bOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZkw2Z0p1a0F5a1BsdElZ
            SEpyVmVRbXdHdlRzU2RkVVJXWGh5eHY1aGhnCjFFYkM3cWdBcmdGckdkZ29hcWRP
            SXFLeFpBN21CZ2FtbnBsaCtPczdWTHcKLS0tIEgrVlNPNEpEM0NoMUZBTFZ2S3lU
            RVFScWRXRTJhN3RxaTBvL0pPQ3ZWd1kKyFCt6S5mtcJArlLOWT5oPZg9Jgejn43C
            2Mazrqk8CL2NAmOxNsFUNuLjvfrap0ovAmg7cdHFiCHUXNiPCFWwQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1llu2lzcdaauzqscewak9jsqdxfut7l77d5kxmaeqkwnxv8zm7cvsen2p6l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T10:19:21Z"
    mac: ENC[AES256_GCM,data:puhOsLvh8BXZFNULJKyotNKKGPnioW5v5n8ZRaI622wapjrFIQCsQbsivvaFYI8ZKDYq9vYfXmdWgfH75fLaunJLMBFl09qTlCSzDDtJBeejxwHDoduf2fYWv/6JfdUaAj4M7AbKZnY/AYZWsRj5ABbOryLoro17IDJO4pwzWgs=,iv:3XQI4hWk8jdrpN6Ku67ZjBzAAZBFbO70pimb2lPOXvE=,tag:11+Rada4Dxall8apNvCO5A==,type:str]
    version: 3.13.2
