apiVersion: gateway.kaddy.io/v1alpha1
kind: Caddy
metadata:
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/part-of: kaddy
    app.kubernetes.io/managed-by: kustomize
  name: edge
spec:
  replicas: 2
  gatewayClassName: caddy
  metrics:
    enabled: true
  admin:
    listen: ":2019"
