apiVersion: gateway.kaddy.io/v1alpha1
kind: Caddy
metadata:
  labels:
    app.kubernetes.io/name: kaddy-operator
    app.kubernetes.io/managed-by: kustomize
  name: caddy-sample
spec:
  # TODO(user): Add fields here
