apiVersion: v1
kind: Secret
metadata:
    name: backstage-github
    namespace: portal
    labels:
        owner: platform-team
        service: portal
        part-of: kaddy
        managed-by: argocd
        app.kubernetes.io/name: backstage-github
        app.kubernetes.io/part-of: kaddy
type: Opaque
stringData:
    AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:XzwANTbPdAVVj4UcUmSOc6rU04w=,iv:Ok6/UpOUTMScxBBTk2ATSe+mryMqCSmZ+uXiwZC+2Z0=,tag:t1DVyL4VscROGklQuw4zDg==,type:str]
    AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:QSpUsENh3emnWKotoIUZwAlNQItUqEwqrXKIjy5+bwSBkrczgsuJaQ==,iv:CyGSXnTiVt0kHFIHOQE48PXMTJYBZK36qeRKfXkBC9A=,tag:Oeo2tQG4gUO/eT73Vr7xQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWHRQbjdBNG5ZSWd4Yk1v
            WFRHTGtadlBocDI2WDh5MHo4Sno4UjZobEJzCld5cVA5ZTd3Y2FUaDlUQ1g2VDRL
            OGhkdE5ySW1oc3lIaHVvVVFkd01zNmMKLS0tIDVySEJBUklJaTJYQmxJM2EyNnNQ
            UEVqM29VV1FSSisxVXBlODhYY0NCVDgK3XS97+v4DSm5M/HV6o/cOpSIWPOcPb1E
            O8t3fRj8iQBREc5w5b5EplotazYEu0BknzAqAx+77iP+h8SHKgYITQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1llu2lzcdaauzqscewak9jsqdxfut7l77d5kxmaeqkwnxv8zm7cvsen2p6l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T07:04:30Z"
    mac: ENC[AES256_GCM,data:JzKvmVMd2kJ4r9Had3pf3Y1nAzwZrKMynx2+rjiVJ93PKT/dfuqdmxIhqPwgM7FXT8cKpVklMdTiOAt/GwlEz5hsko+fBlWGYl7GOhNLJcSW4NfDE7/BQykr1MHYvgVFDWdB/etz0cwpa7z38K/Xz/XdIt1JC0wHMrOXYX3WOqY=,iv:8NH7CsOZcE/iYRL5z0VI7X5IWUTUP+SKTg1/87hVCN8=,tag:uNeZ/9iv1L8BnxS8dHhQ0w==,type:str]
    version: 3.13.2
