apiVersion: v1
kind: Secret
metadata:
    name: dex-github-oauth
    namespace: identity
    labels:
        app.kubernetes.io/name: dex
        app.kubernetes.io/component: oauth
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:EHNJOipPw8DIA55OGameCcBjlbc=,iv:xJkRAEpmJP0rYstC2ZxuI6POv8Mue7VEyqlSE5/7rMc=,tag:Jdyj5IYitCjMZjWvvmnk6g==,type:str]
    client-secret: ENC[AES256_GCM,data:Nn2tj9i/uzp3i3W2GF4gkoJvj7Z4MfReHSawbjmq6vBaVlnWbLrrGg==,iv:cGO1ytywFUjRfMaX7umvixg1QjuNvyOu/GnJI0kXtUk=,tag:e0dQkcqPhL5szatjAQ957g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TEV2czlKd0lDV04veUxZ
            RENFWSs2TWlNcjVSc2RuK0RNUjluSkM2UDE0CitzS0l4c0IvWCtDYnU4d1BQcTJL
            V1Bpc0c5d1ZFRngzOS9ncGZFMUMxUW8KLS0tIDlRcy9zdWIvTWlFbEV0d0pmWHQ2
            RzgvVGFSMkxGLzlJQXVTeVdDbUc5MlkKArVeK9RxEMGS19QsyubdPbNvobqxzYON
            yOi9CPBtZEbRwmxSF4E7sKzxLX+4RML+yPIWuZ04LHt6BTs/qi50Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1llu2lzcdaauzqscewak9jsqdxfut7l77d5kxmaeqkwnxv8zm7cvsen2p6l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T14:01:18Z"
    mac: ENC[AES256_GCM,data:zoRJpyz1liyX4CH7a8/R764y0TQsuKFU0QtthBXbxp+Qt0VmGuHzt9YnqRFQkW6DyBlqhLLvFGZQrHejgvzVazKBORnwXpV4KYD4N7ciIXiXbgYOVnd7n4+Nq2CifUgj3zUzcTTbBEqc46/rwYjiHhkdts/gxD3NgntDN4/VGm4=,iv:uRusUanWV+6Pmj1npAaASvslJhdIaqnNQRSzg3KeJM0=,tag:42ib09uvHNKYxELv6GBY4A==,type:str]
    version: 3.13.2
