apiVersion: v1
kind: Secret
metadata:
    name: dex-clients
    namespace: identity
    labels:
        app.kubernetes.io/name: dex
        app.kubernetes.io/component: oidc-clients
type: Opaque
stringData:
    argocd-client-secret: ENC[AES256_GCM,data:eGz2uMsCKIOPbz7h7vJwo+CXeYQHyGXoANMdnGXPRD2NeuD1NLrKvqsZEgb0lNAKSRMlKBOl5TlFRH9TyChw/Q==,iv:Yeh3IOBJJZ28wTUjOQzM2BmzbhF7XPhdxvldpuVEDOc=,tag:V/RDietA/CGrmu3JdWd0Dw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQXVCZGlUUDdGcFd6T2Vx
            OVY1RjgvWUVwdW9wZXE0UnFsLzhNT2gvZUN3CmJsVFd4bnQ4RWhYWldLU2JKUHMz
            MDZWajBqTzZqOExxaUhQNmovNC9BeW8KLS0tIGdkQlFBWGxkMjJjbnoxQXVGME9F
            c1hJL1J0bWp3UXc4N3VlaXhxM0cvelkKS8zO0PwI6z9RWc/JQ6yBkXHySQkIIcer
            yJ2NjDfy0/BPvUFsKhjbiuN9rN0xBCaxDkIlDgAXpmUcSZlcB6ZmtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1llu2lzcdaauzqscewak9jsqdxfut7l77d5kxmaeqkwnxv8zm7cvsen2p6l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T10:19:21Z"
    mac: ENC[AES256_GCM,data:wHARcyeCO78ALuyemYxXP0Avb5xzVt0oTSaIeBggmjh6y4JtVQpDCAf4QXznEWcl8go//DYwwvdQnZP/5p7EaLIu50cLmmzOEHrRtL4zB0brvUI8HIq6Fo7daHs1LjCgUYlVc3Jod71xXCFRAA1VhTdPOmkhqEhpbYLtC9H/1LA=,iv:mn9IM1xCcPNQZalH1Gt24t/8Y5A2M3hh7pSKnTRuYsE=,tag:BtltBw2huq7mXavIPfeDNg==,type:str]
    version: 3.13.2
